### ISSUE TITLE
Unpickling errors when loading models

### ISSUE THREAD

**Issue by mttk** [HazyResearch/H3#11]
Hi,

when loading pretrained models from checkpoints using the `generate_text_h3` script I'm getting the following issue: 

```
Traceback (most recent call last):
  File "H3/examples/generate_text_h3.py", line 41, in <module>
    state_dict = torch.load(args.ckpt, map_location=device)
  File "/home/.../.conda/envs/work/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/.../.conda/envs/work/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
Python version = 3.8.2
torch version = 1.13.1

Any ideas what I might be doing wrong? Likely a versioning issue

**Comment by mttk** [comment]
File got malformed during download, disregard :)
